#!/usr/bin/python3
add_integer = __import__('0-add_integer').add_integer

print(add_integer(7, 3))
print(add_integer(7.0, 3.0))
print(add_integer(0))
print(add_integer(2.0,))
print(add_integer(-5.5,100.3))
print(add_integer('a', 3))
print(add_integer(2,['A', 'B', 'C']))
print(add_integer({'a':1},))
print(add_integer('a', 'b'))
print(add_integer(float('inf')))
print(add_integer(4, float('inf')))
print(add_integer(float('inf'), 4))
print(add_integer(float('NaN')))
print(add_integer(float('NaN'), 5))
print(add_integer(5, float('NaN')))
print(add_integer(2,['A', 'B', 'C']))
print(add_integer({'a':1},))
print(add_integer('a', 'b'))
print(add_integer(float('NaN')))
print(add_integer(float('NaN'), 5))
print(add_integer(5, float('NaN')))
print(add_integer(float('inf')))
print(add_integer(4, float('inf')))
print(add_integer(float('inf'), 4))
